config/routes.rb
Rails.application.routes.draw do
  # topページとテストのルーティング
  root 'static_pages#top'
  # get 'test', to: 'static_pages#test'
  # get 'merge', to: 'static_pages#top_merge'
  get 'terms', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # 診断関係のルーティング
  get 'diagnoses/new'
  post 'diagnoses/index'
  
  # ログイン関連のルーティング
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'

  # 会員登録のルーティング
  resources :users, only: [:new, :create]

  #投稿関係のルーティング
  resources :boards do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'bookmarks'
    end
  end

  # お気に入り投稿のルーティング
  resources :bookmarks, only: %i[create destroy]

  # Dog関連のルーティング
  resources :dogs, only: [:show, :index]
end

app/models/comment.rb
class Comment < ApplicationRecord
  #他テーブルとのアソシエーション
  belongs_to :user
  belongs_to :board

  #validationの設定
  validates :body, presence: true, length: { maximum: 65_535 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
      
        @comment = current_user.comments.build(comment_params)
        @board = Board.find(params[:board_id])  # コメントが属する掲示板を取得
      
        # respond_to do |format|
        #   if @comment.save
        #     format.html { redirect_to @board, notice: 'Comment was successfully created.' }
        #     format.json { render :show, status: :created, location: @comment }
        #     format.js   # ここで JS フォーマットを指定
        #   else
        #     format.html { render 'boards/show', locals: { board: @board } }  # エラー時の処理
        #     format.json { render json: @comment.errors, status: :unprocessable_entity }
        #     format.js   # エラー時も JS フォーマットを指定
        #   end
        # end

        respond_to do |format|
          if @comment.save
            format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_index_area', partial: 'comments/comments', locals: { comments: @comments }) }
          else
            format.html { redirect_to board_path(@board), notice: 'Comment was not saved.' }
          end
        end
      end      

    def destroy
        @comment = current_user.comments.find(params[:id])
        @comment.destroy!
    end

    private

    def comment_params
        params.require(:comment).permit(:body).merge(board_id: params[:board_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <%= image_tag 'sample.jpg', class: 'rounded-circle', size: '50x50' %>
  </td>
  <td>
    <h3 class="small"><%= comment.user.decorate.user_san %></h3>
    <div id="js-comment-<%= comment.id %>">
      <%= simple_format(comment.body) %>
    </div>
    <div class="small text-muted" id="js-comment-time-<%= comment.id %>">
      <%= t('activerecord.attributes.comment.created_at') %>
      <%= l comment.created_at, format: :long %>
    </div>
  </td>

  <% if logged_in? %>
    <% if current_user.own?(comment) %>
      <td class="action">
        <ul class="list-inline justify-content-center" style="float: right;">
          <li class="list-inline-item">
            <%= link_to comment_path(comment),
                        class: 'js-delete-comment-button',
                        method: :delete,
                        data: { confirm: t('defaults.message.delete_confirm') } do %>
              <%= icon 'fas', 'trash' %>
              <%= t('comments.form.comment_delete') %>
            <% end %>
          </li>
        </ul>
      </td>
    <% end %>
  <% end %>
</tr>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table id="js-table-comment" class="table">
      <%# render partial: 'comment', collection: comments の省略 %>
      <%= render comments %>
    </table>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: board_comments_path(board), id: 'new_comment',local: false, remote: true, data: { turbo_method: :post } do |f| %>
      <%# render 'shared/error_messages', object: f.object 　←Ajax化に伴いこのエラーメッセージもコメントアウトする%>
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control mb-3', id: 'js-new-comment-body', row: 4,  placeholder: Comment.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
<%# すでにエラー文が表示されていたら、一旦削除する %>
$("#error_messages").remove()
<% if @comment.errors.present? %>
  <%# // エラー時の処理 %>
  $("#new_comment").prepend("<%= j(render('shared/error_messages', object: @comment)) %>");
<% else %>
  <%# // 正常時の処理 %>
  $("#js-table-comment").prepend("<%= j(render('comments/comment', comment: @comment)) %>");
  $("#js-new-comment-body").val('');
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update 'new_comment_area' do %>
    <%= render 'comments/form', { board: @board, comment: @comment } %>
<% end %>

<%= turbo_stream.update 'comment_index_area' do %>
    <%= render 'comments/comments', { comments: @comments } %>
<% end %>

app/views/comments/destroy.js.erb
$("tr#comment-<%= @comment.id %>").remove()