config/routes.rb
Rails.application.routes.draw do
  # topページとテストのルーティング
  root 'static_pages#top'
  # get 'test', to: 'static_pages#test'
  # get 'merge', to: 'static_pages#top_merge'
  get 'terms', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # 診断関係のルーティング
  get 'diagnoses/new'
  post 'diagnoses/index'
  
  # ログイン関連のルーティング
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'

  # 会員登録のルーティング
  resources :users, only: [:new, :create]

  #投稿関係のルーティング
  resources :boards do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'bookmarks'
    end
  end

  # お気に入り投稿のルーティング
  resources :bookmarks, only: %i[create destroy]

  # Dog関連のルーティング
  resources :dogs, only: [:show, :index]
end

app/models/answer.rb
class Answer < ApplicationRecord
    #外部キーの設定
    belongs_to :question
    has_many :dog_answer_rerationships, dependent: :destroy
    has_many :dogs, through: :dog_answer_rerationships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :board_image, BoardImageUploader
  #他テーブルとの関係性
  belongs_to :user
  belongs_to :dog
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  #validation関係
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  #ransackの検索機能を使うために下記のメソッドを追加、どの属性や関連を検索可能とするかを指定する
  #特にこれは属性に関しての記述
  def self.ransackable_attributes(auth_object = nil)
    ["board_image", "body", "created_at", "dog_id", "id", "id_value", "title", "updated_at", "user_id"]
  end

  #ransackの検索機能を使うために下記のメソッドを追加、どの属性や関連を検索可能とするかを指定する
  #特にこれは関連に関しての記述
  def self.ransackable_associations(auth_object = nil)
    ["comments", "dog", "user"]
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :user_id, uniqueness: { scope: :board_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  #他テーブルとのアソシエーション
  belongs_to :user
  belongs_to :board

  #validationの設定
  validates :body, presence: true, length: { maximum: 65_535 }

end

app/models/dog.rb
class Dog < ApplicationRecord
    #uploaderクラスの紐付け
    mount_uploader :dog_image, DogImageUploader
    #外部キーの設定
    belongs_to :dog_size_type
    belongs_to :dog_country
    has_many :dog_answer_rerationships, dependent: :destroy
    has_many :answers, through: :dog_answer_rerationships
    has_many :boards

    #バリデーションの設定
    validates :breed, presence: true

    #enumの設定
    enum hair_length: { short_hair: 0, medium_hair: 1, long_hair: 2, short_or_long_hair: 3 }
    enum activity_level: { low_activity_level: 0, middle_activity_level: 1, high_activity_level: 2 }
    enum solitude_tolerance: { low_solitude_tolerance: 0, middle_solitude_tolerance: 1, high_solitude_tolerance: 2 }
    enum care_difficulty: { easy_care_difficulty: 0, middle_care_difficulty: 1, difficult_care_difficulty: 2 }     
    
    #attr_accessor(一時的なカラム、DB保存なし)の設定
    attr_accessor :temp_count

    #ransackの検索機能を使うために下記のメソッドを追加、どの属性や関連を検索可能とするかを指定する
    #特にこれは属性に関しての記述
    def self.ransackable_attributes(auth_object = nil)
        ["name", "activity_level", "breed", "care_difficulty", "catchphrase", "created_at", "dog_country_id", "dog_image", "dog_size_type_id", "features_sentence", "hair_length", "height", "history_sentence", "id", "id_value", "personality_sentence", "recommended_for_whom", "solitude_tolerance", "updated_at", "weight", "display_in_index"]
    end
    
end

app/models/dog_country.rb
class DogCountry < ApplicationRecord
    has_many :dogs
end

app/models/dog_size_type.rb
class DogSizeType < ApplicationRecord
    has_many :dogs, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  #認証関係のバリデーション
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true

  #他テーブルとの関係性
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_boards, through: :bookmarks, source: :board

  #current_userかどうか判定する
  def own?(object)
    id == object.user_id
  end

  # ブックマークに追加する
  def bookmark(board)
    bookmark_boards << board
  end

  # ブックマークを外す
  def unbookmark(board)
    bookmark_boards.destroy(board)
  end

  # ブックマークをしているか判定する
  def bookmark?(board)
    bookmark_boards.include?(board)
  end
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  skip_before_action :require_login, only: [:new, :index ]
  def new
    @questions = Question.all.includes(:answers).order(id: :asc)
  end

  def index
    # ユーザーの回答の question.answersの:idを配列であるanswersに格納されているので、int型で格納しなおす
    @user_answers_array = params[:answers].reject(&:blank?).map(&:to_i)
  
    # @match_dogに該当するdog_idとカウントをハッシュ形式で格納していく
    @dog_with_temp_count_array = []

    # ユーザーの回答（answer_id）と、DogAnswerRerationship の answer_id が合致するレコードを全て取得する
    @matching_records = DogAnswerRerationship.none  # 空のActiveRecordリレーションを作成する
    @user_answers_array.each do |user_answer|  
      matching_records_for_answer = DogAnswerRerationship.where(answer_id: user_answer)
      @matching_records = @matching_records.or(matching_records_for_answer)  # 合致するレコードを追加
    end

    # 取得したレコードに対して dog_id 毎にカウントを取る,格納されている形はハッシュで、{dog_id: count}の形で格納されている
    count_by_dog_id = @matching_records.group(:dog_id).count

    # attr_accessorの:temp_countにマッチした回答数を格納する
    count_by_dog_id.each do |dog_id, match_count|
      dog_with_temp_count = Dog.find_by(id: dog_id)
      dog_with_temp_count.temp_count = match_count
      @dog_with_temp_count_array << dog_with_temp_count
    end

    # 最大のtemp_count(回答マッチ数)の値を取得する
    max_temp_count = @dog_with_temp_count_array.map(&:temp_count).max
    # 最大のtemp_countを持つ犬種のみに絞る
    @recommend_dogs = @dog_with_temp_count_array.select { |dog| dog.temp_count == max_temp_count }
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]

  def index
    @displayed_dogs = Dog.where(display_in_index: 1)
    @displayed_dogs_pulldown = @displayed_dogs.order(breed: :asc).pluck(:breed).uniq
    @q = @displayed_dogs.ransack(params[:q])
    @dogs = @q.result(distinct: true).includes(:dog_size_type, :dog_country).order(breed: :asc) 
  end

  def show
    @dog = Dog.includes(:dog_size_type, :dog_country).find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(user_params[:email], user_params[:password]) #ユーザー登録後ログインを自動で行う
            redirect_back_or_to root_path, success: '会員登録が完了しました'
        else
            flash.now[:danger] = '会員登録に失敗しました'
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title(page_title = '')
        base_title = 'TailTales'

        page_title.empty? ? base_title : page_title + ' | ' + base_title
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diagnoses/_question.html.erb
<div class="form-group question-container">
  <%= content_tag :strong, "Q. #{question.content}", class: 'question-text' %>
  <%# answesというname属性の配列に回答を格納する %>
  <%= f.collection_select "answers[]", question.answers, :id, :content, { prompt: "回答を選択してください" }, { class: 'form-control' } %>
</div>

app/views/diagnoses/_recommend_dog.html.erb
<main class="container">

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
    <circle cx="12" cy="12" r="10"/>
    <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/>
  </symbol>
  <symbol id="cart" viewBox="0 0 16 16">
    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
  <symbol id="chevron-right" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
  </symbol>
</svg>


  <div class="row mb-2">
    <div class="col-md-12">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">
          <%= "おすすめ度：" %>
          <% recommend_dog.temp_count.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
          </strong>
          <h3 class="mb-0"><%= recommend_dog.breed %></h3>
          <div class="mb-1 text-body-secondary"><%= recommend_dog.dog_size_type.name %></div>
          <h5 class="card-text mb-auto"><%= recommend_dog.catchphrase %></h5>
          <%= link_to(dog_path(recommend_dog.id), class: "icon-link gap-1 icon-link-hover stretched-link") do %>
            <%= "#{recommend_dog.breed}の詳細はこちら" %>
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          <% end %>
        </div>
        <div class="col-auto d-none d-lg-block">
          <%= image_tag "dog_image/#{recommend_dog.id}.jpeg", class: 'bd-placeholder-img', size: '200x200' %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/diagnoses/index.html.erb
<h1>診断結果</h1>

<% if @recommend_dogs.present? %>
  <%= render partial: "recommend_dog", collection: @recommend_dogs %>
<% else %>
  <p><%= t('.no_match') %></p>
<% end %>

app/views/diagnoses/new.html.erb
<div class="container pt-3 pb-3 diagnoses-container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <%= form_with url: diagnoses_index_path, method: :post, local: true do |f| %> 
        <%= render partial: 'diagnoses/question', collection: @questions, locals: { f: f } %>
        <%= f.submit '診断結果へ', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>