config/routes.rb
Rails.application.routes.draw do
  # topページとテストのルーティング
  root 'static_pages#top'
  # get 'test', to: 'static_pages#test'
  # get 'merge', to: 'static_pages#top_merge'
  get 'terms', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # 診断関係のルーティング
  get 'diagnoses/new'
  post 'diagnoses/index'
  
  # ログイン関連のルーティング
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'

  # 会員登録のルーティング
  resources :users, only: [:new, :create]

  #投稿関係のルーティング
  resources :boards do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'bookmarks'
    end
  end

  # お気に入り投稿のルーティング
  resources :bookmarks, only: %i[create destroy]

  # Dog関連のルーティング
  resources :dogs, only: [:show, :index]
end

app/models/answer.rb
class Answer < ApplicationRecord
    #外部キーの設定
    belongs_to :question
    has_many :dog_answer_rerationships, dependent: :destroy
    has_many :dogs, through: :dog_answer_rerationships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :board_image, BoardImageUploader
  #他テーブルとの関係性
  belongs_to :user
  belongs_to :dog
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  #validation関係
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  #ransackの検索機能を使うために下記のメソッドを追加、どの属性や関連を検索可能とするかを指定する
  #特にこれは属性に関しての記述
  def self.ransackable_attributes(auth_object = nil)
    ["board_image", "body", "created_at", "dog_id", "id", "id_value", "title", "updated_at", "user_id"]
  end

  #ransackの検索機能を使うために下記のメソッドを追加、どの属性や関連を検索可能とするかを指定する
  #特にこれは関連に関しての記述
  def self.ransackable_associations(auth_object = nil)
    ["comments", "dog", "user"]
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :user_id, uniqueness: { scope: :board_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  #他テーブルとのアソシエーション
  belongs_to :user
  belongs_to :board

  #validationの設定
  validates :body, presence: true, length: { maximum: 65_535 }

end

app/models/dog.rb
class Dog < ApplicationRecord
    #uploaderクラスの紐付け
    mount_uploader :dog_image, DogImageUploader
    #外部キーの設定
    belongs_to :dog_size_type
    belongs_to :dog_country
    has_many :dog_answer_rerationships, dependent: :destroy
    has_many :answers, through: :dog_answer_rerationships
    has_many :boards

    #バリデーションの設定
    validates :breed, presence: true

    #enumの設定
    enum hair_length: { short_hair: 0, medium_hair: 1, long_hair: 2, short_or_long_hair: 3 }
    enum activity_level: { low_activity_level: 0, middle_activity_level: 1, high_activity_level: 2 }
    enum solitude_tolerance: { low_solitude_tolerance: 0, middle_solitude_tolerance: 1, high_solitude_tolerance: 2 }
    enum care_difficulty: { easy_care_difficulty: 0, middle_care_difficulty: 1, difficult_care_difficulty: 2 }     
    
    #attr_accessor(一時的なカラム、DB保存なし)の設定
    attr_accessor :temp_count

    #ransackの検索機能を使うために下記のメソッドを追加、どの属性や関連を検索可能とするかを指定する
    #特にこれは属性に関しての記述
    def self.ransackable_attributes(auth_object = nil)
        ["name", "activity_level", "breed", "care_difficulty", "catchphrase", "created_at", "dog_country_id", "dog_image", "dog_size_type_id", "features_sentence", "hair_length", "height", "history_sentence", "id", "id_value", "personality_sentence", "recommended_for_whom", "solitude_tolerance", "updated_at", "weight", "display_in_index"]
    end
    
end

app/models/dog_country.rb
class DogCountry < ApplicationRecord
    has_many :dogs
end

app/models/dog_size_type.rb
class DogSizeType < ApplicationRecord
    has_many :dogs, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  #認証関係のバリデーション
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true

  #他テーブルとの関係性
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_boards, through: :bookmarks, source: :board

  #current_userかどうか判定する
  def own?(object)
    id == object.user_id
  end

  # ブックマークに追加する
  def bookmark(board)
    bookmark_boards << board
  end

  # ブックマークを外す
  def unbookmark(board)
    bookmark_boards.destroy(board)
  end

  # ブックマークをしているか判定する
  def bookmark?(board)
    bookmark_boards.include?(board)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]

  def index
    @displayed_dogs = Dog.where(display_in_index: 1)
    @displayed_dogs_pulldown = @displayed_dogs.order(breed: :asc).pluck(:breed).uniq
    @q = @displayed_dogs.ransack(params[:q])
    @dogs = @q.result(distinct: true).includes(:dog_size_type, :dog_country).order(breed: :asc) 
  end

  def show
    @dog = Dog.includes(:dog_size_type, :dog_country).find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(user_params[:email], user_params[:password]) #ユーザー登録後ログインを自動で行う
            redirect_back_or_to root_path, success: '会員登録が完了しました'
        else
            flash.now[:danger] = '会員登録に失敗しました'
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title(page_title = '')
        base_title = 'TailTales'

        page_title.empty? ? base_title : page_title + ' | ' + base_title
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# 以下が追加したもの %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" %>
    
    <%= favicon_link_tag "favicon.ico" %> <%# titleのアイコンを挿入する %>
    


  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else%>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class='navbar-brand' href='/'>
      <%= image_tag 'logo.png', size: '80x80' %>
    </a>
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to '犬種マッチ診断', diagnoses_new_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to '犬種一覧', dogs_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('boards.index.title'), boards_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログイン', login_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger", id='error_messages'>
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">&copy; 2024 Company, Inc</p>
    <ul class="nav col-md-4 nav-center">
      <i class="fa-solid fa-chevron-up"></i>
      <li><a href="#" class="px-2 text-body-secondary up_to_top">一番上まで</a></li>
      <i class="fa-solid fa-chevron-up"></i>
    </ul>
    <ul class="nav col-md-4 justify-content-end">
      <li><%= link_to "お問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLScZ9fRjj74hMN2K7Tx_NmTUodrih28gMOJ-u_7_CSqdtfXgxQ/viewform", class: "px-2 text-body-secondary" %></li>
      <li><%= link_to "利用規約", terms_path, class: "px-2 text-body-secondary" %></li>
      <li><%= link_to "プライバシーポリシー", privacy_policy_path, class: "px-2 text-body-secondary" %></li>
    </ul>
  </footer>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class='navbar-brand' href='/'>
      <%= image_tag 'logo.png', size: '80x80' %>
    </a>
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to '犬種マッチ診断', diagnoses_new_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to '犬種一覧', dogs_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('boards.index.title'), boards_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('boards.bookmarks.title'), bookmarks_boards_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('boards.new.title'), new_board_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', logout_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>