config/routes.rb
Rails.application.routes.draw do
  # topページとテストのルーティング
  root 'static_pages#top'
  # get 'test', to: 'static_pages#test'
  # get 'merge', to: 'static_pages#top_merge'
  get 'terms', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # 診断関係のルーティング
  get 'diagnoses/new'
  post 'diagnoses/index'
  
  # ログイン関連のルーティング
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'

  # 会員登録のルーティング
  resources :users, only: [:new, :create]

  #投稿関係のルーティング
  resources :boards do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'bookmarks'
    end
  end

  # お気に入り投稿のルーティング
  resources :bookmarks, only: %i[create destroy]

  # Dog関連のルーティング
  resources :dogs, only: [:show, :index]
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :board_image, BoardImageUploader
  #他テーブルとの関係性
  belongs_to :user
  belongs_to :dog
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  #validation関係
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  #ransackの検索機能を使うために下記のメソッドを追加、どの属性や関連を検索可能とするかを指定する
  #特にこれは属性に関しての記述
  def self.ransackable_attributes(auth_object = nil)
    ["board_image", "body", "created_at", "dog_id", "id", "id_value", "title", "updated_at", "user_id"]
  end

  #ransackの検索機能を使うために下記のメソッドを追加、どの属性や関連を検索可能とするかを指定する
  #特にこれは関連に関しての記述
  def self.ransackable_associations(auth_object = nil)
    ["comments", "dog", "user"]
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[edit update destroy]
  skip_before_action :require_login, only: [:index, :show]

  def new
    @board = Board.new
    @dogs = Dog.order(breed: :asc)
  end

  def create
    @board = current_user.boards.build(board_params)
    
    if @board.save
      redirect_to boards_path, success: '投稿しました'
    else
      flash.now['danger'] = '投稿失敗しました'
      render :new
    end
  end

  def index
    @dog_breeds = Dog.pluck(:breed).uniq #pluckで:breedのカラムの値のみを配列で取得、重複はないけどuniqで取得。
    @q = Board.ransack(params[:q]) #ransackメソッドは、送られてきたパラメーターを元にテーブルからデータを検索するメソッドです。(whereメソッドのransack版というイメージです。)
    @boards = @q.result(distinct: true).includes(:user, :dog).order(created_at: :desc) #ransackメソッドで取得したデータをActiveRecord_Relationのオブジェクトに変換するメソッドです。
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new
    @comments = @board.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    @dogs = Dog.order(breed: :asc)
  end

  def update
    if @board.update(board_params)
      redirect_to @board, success: t('defaults.message.updated', item: Board.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Board.model_name.human)
      render :edit
    end
  end

  def destroy
    @board.destroy!
    redirect_to boards_path, success: t('defaults.message.deleted', item: Board.model_name.human)
  end

  def bookmarks
    @dog_breeds = Dog.pluck(:breed).uniq #pluckで:breedのカラムの値のみを配列で取得、重複はないけどuniqで取得。 
    @q = current_user.bookmark_boards.ransack(params[:q])
    @bookmark_boards = @q.result(distinct: true).includes(:user, :dog).order(created_at: :desc)
  end

  private

  def set_board
    @board = current_user.boards.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :body, :dog_id, :board_image, :board_image_cache)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div class="row mb-2">
  <div class="col-md-12">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      
      <!-- 画像の列 -->
      <div class="col-md-auto order-md-first">
        <%= image_tag board.board_image_url, class: 'bd-placeholder-img', size: '200x200' %>
      </div>
      
      <!-- 情報の列 -->
      <div class="col p-4 d-flex flex-column position-static">
        <strong class="d-inline-block mb-0 text-primary-emphasis">
          <%= board.user.decorate.user_san %>
        </strong>
        <strong class="d-inline-block mb-0 text-primary-emphasis">
          <%= "#{t('activerecord.attributes.board.created_at')}：#{l board.created_at, format: :long}" %>
        </strong>
        
        <h2 class="mb-2"><%= link_to board.title, board_path(board)  %></h2>
        
        <!-- ドッグ情報 -->
        <%= link_to dog_path(board.dog), class: "d-flex align-items-center text-decoration-none" do %>
          <i class="fa-solid fa-dog me-2 text-primary" style="font-size: 1.3em;"></i>
          <div>
            <h6 class="card-text mb-auto"><%= board.dog.breed %></h6>
          </div>
        <% end %>

        <!-- ログインユーザーにのみ表示されるメニュー -->
        <div class="mt-2">
          <% if logged_in? %>
            <% if current_user.own?(board) %>
              <%= render 'crud_menus', board: board %>
            <% else %>
              <%= render 'bookmark_button', board: board %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/_bookmark.html.erb
<%= link_to bookmarks_path(board_id: board.id), 
            id: "js-bookmark-button-for-board-#{board.id}", 
            class:"float-right", 
            method: :post, 
            remote: true do %>
  <%= icon 'far', 'heart' %>
<% end %>

app/views/boards/_bookmark_button.html.erb
<% if current_user.bookmark?(board) %>
    <%= render 'unbookmark', board: board %>
<% else %>
    <%= render 'bookmark', board: board %>
<% end %>

app/views/boards/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right m-0'>
  <li class="list-inline-item">
    <%= link_to edit_board_path(board), id: "button-edit-#{board.id}" do %>
      <%= icon 'fa', 'pen' %>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to board_path(board), id: "button-delete-#{board.id}", method: :delete, data: { confirm: t('defaults.message.delete_confirm') } do %>
      <%= icon 'fas', 'trash' %>
    <% end %>
  </li>
</ul>

app/views/boards/_form.html.erb
<%= form_with model: board, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', rows: 10 %>
    </div>
    <div class="form-group">
      <%= f.label :dog_id, t('boards.new.what_breed') %>
      <%= f.collection_select :dog_id, @dogs, :id, :breed, { prompt: t('boards.new.what_breed_prompt') }, class: 'form-control' %>
    </div>
  <div class="form-group">
    <%= f.label :board_image %>
    <%= f.file_field :board_image, id: 'board_board_image', class: 'form-control mb-3', accept: 'image/*' %>
    <%= f.hidden_field :board_image_cache %>
  </div>
  <div class="mt-3 mb-3">
	  <%# 以下はプレビュー画面を表示するコード %>
    <%= image_tag board.board_image.url, id: 'preview', size: '200x200' %>
    <%= javascript_include_tag 'board_form' %>
  </div>
   <%= f.submit t('defaults.message.to_post'), class: 'btn btn-primary' %>
 <% end %>

app/views/boards/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class="input-group mb-3">
    <%= f.select :dog_breed_eq, @dog_breeds, { include_blank: t('defaults.message.select_dog_breed') }, class: "form-control" %>
    <%= f.search_field :title_or_body_cont, class: "form-control", placeholder: t('defaults.message.search_word') %>
    <div class="input-group-append">
      <input type="submit" value="検索" class="btn btn-primary" />
    </div>
  </div>
<% end %>

app/views/boards/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(board_id: board.id)), 
            id: "js-bookmark-button-for-board-#{board.id}", 
            class:"float-right", 
            method: :delete, 
            remote: true do %>
  <%= icon 'fas', 'heart' %>
<% end %>

app/views/boards/bookmarks.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 col-md-12">
      <!-- 投稿作成誘導ボタン -->
      <div class="d-grid gap-2 mb-2">
        <%= link_to t('boards.new.post'), new_board_path, class: "btn btn-outline-primary", role: "button" %>
      </div>
      <!-- 検索フォーム -->
      <%= content_tag(:div, class: 'mb-1') do %>
        <%= content_tag(:i, nil, class: 'fas fa-search', style: 'margin-right: 5px;') %> 投稿検索
      <% end %>
      <%= render 'search_form', url: bookmarks_boards_path %>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @bookmark_boards.present? %>
          <%= render @bookmark_boards %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { board: @board } %>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 col-md-12">
      <!-- 投稿作成誘導ボタン -->
      <% if logged_in? %>
        <div class="d-grid gap-2 mb-2">
          <%= link_to t('boards.new.post'), new_board_path, class: "btn btn-outline-primary", role: "button" %>
        </div>
      <% else %>
        <div class="d-grid gap-2 mb-2">
          <%= link_to t('boards.new.before_login_post'), new_board_path, class: "btn btn-outline-primary", role: "button" %>
        </div>
      <% end %>
      <!-- 検索フォーム -->
      <%= content_tag(:div, class: 'mb-1') do %>
        <%= content_tag(:i, nil, class: 'fas fa-search', style: 'margin-right: 5px;') %> 投稿検索
      <% end %>
      <%= render 'search_form', url: boards_path %>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @boards.present? %>
          <%= render @boards %>
        <% else %>
          <p><%= t('boards.bookmarks.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { board: @board } %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-3'>
              <%= image_tag @board.board_image.url, class: 'card-img-top img-fluid', size: '200x200' %>
            </div>
            <div class='col-md-9'>
              <h3 class="d-inline"><%= @board.title %></h3>
              <% if logged_in? %>
                <%= render 'crud_menus', board: @board if current_user.own?(@board) %>
              <% end %>
              <ul class="list-inline">
                <li class="list-inline-item">by <%= @board.user.decorate.user_san %></li>
                <li class="list-inline-item"><%= t('activerecord.attributes.board.created_at') %>：<%= l @board.created_at, format: :long  %></li>
              </ul>
            </div>
          </div>
          <p><%= simple_format(@board.body) %></p>
        </div>
      </article>
    </div>
  </div>

  <!-- コメントフォーム -->
    <% if logged_in? %>
      <%= render 'comments/form', { board: @board, comment: @comment } %>
    <% end %>

  <!-- コメントエリア -->
    <%= render 'comments/comments', { comments: @comments } %>

  <%# 投稿一覧に戻るボタンの設置 %>
  <div class='text-center'>
    <%= link_to t('.to_board_index'), boards_path %>
  </div>
</div>